name: Add Monitor Uptimerobot

on:
  push:
    branches: main
    
jobs:
  Add_Uptimerobot_monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create URL monitor
        uses: yojota/uptimerobot-addmonitor@v1.7
        with:
          url_monitor: "https://yojota.cloud"
          api_uptimerobot: ${{ secrets.API_UPTIMEROBOT }}
