name: Add Monitor Uptimerobot

on:
  push:
    branches: main
    
jobs:
  Add_Uptimerobot_monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Create URL monitor
        uses: yojota/uptimerobot-addmonitor@v1.2
        with:
          url_monitor: "https//yojota.cloud"
          API_uptimerobot: ${{ secrets.API_uptimerobot }}
